repos:
  # Pre-commit hooks: Basic formatting checks (whitespace and newlines)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: k8s/
      - id: end-of-file-fixer
        exclude: k8s/

  # Local repository for running Terraform checks
  - repo: local
    hooks:
      - id: terraform
        require_serial: true
        name: terraform
        entry: .pre-commit-hooks.d/terraform.sh
        language: script
        files: ^.*(\.tf)$

  # Black: Automatically formats Python code, run on all .py files in lambda_function_files and subdirectories
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: ^lambda_function_files/.*\.py$

  # Pre-commit hooks: Basic formatting checks (whitespace and newlines), run on all .py files in lambda_function_files and subdirectories
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ^lambda_function_files/.*\.py$
      - id: end-of-file-fixer
        files: ^lambda_function_files/.*\.py$

  # Markdown linting hook: Lint markdown files, automatically fixing issues
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        args: ["--fix"]

minimum_pre_commit_version: !!str 2.19
