name: 'PR Checks'

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

env:
  PRE_COMMIT_VERSION: 2.19.*
  TERRAFORM_DOCS_VERSION: 0.19.0

jobs:
  # Job to render terraform docs and push changes back to the PR
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform-docs
        run: |
          cd /tmp
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v"${TERRAFORM_DOCS_VERSION}"/terraform-docs-v"${TERRAFORM_DOCS_VERSION}"-"$(uname)"-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mv terraform-docs "${HOME}/.local/bin"
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: ./apiGateway, ./lambda
          output-method: inject
          indentation: 3
          args: --hide header --anchor=false
          git-push: "true"
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: ${{ github.event.pull_request.head.ref }}

  # Job to run pre-commit hooks on the codebase
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install pre-commit
        run: |
          pip3 install --upgrade --user --disable-pip-version-check "pre-commit==${PRE_COMMIT_VERSION}"
          echo "${HOME}/.local/bin" >>"${GITHUB_PATH}"
      - name: Run pre-commit
        run: |
          if ! pre-commit run --all-files
          then
            git diff || true
            exit 1
          fi
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: ${{ github.event.pull_request.head.ref }}
